sub+: '{"command":"subscribe","topic":"/myhome/grandfloor/+room/temperature"}'
sub#: '{"command":"subscribe","topic":"/myhome/grandfloor/#"}'
sub-kitchen: '{"command":"subscribe","topic":"/myhome/grandfloor/kitchen/temperature"}'
sub-bedroom: '{"command":"subscribe","topic":"/myhome/grandfloor/bedroom/temperature"}'
unsub+: '{"command":"unsubscribe","topic":"/myhome/grandfloor/+room/temperature"}'
unsub#: '{"command":"unsubscribe","topic":"/myhome/grandfloor/#"}'
unsub-kitchen: '{"command":"unsubscribe","topic":"/myhome/grandfloor/kitchen/temperature"}'
unsub-bedroom: '{"command":"unsubscribe","topic":"/myhome/grandfloor/bedroom/temperature"}'
pub-kitchen: '{"command":"publish","topic":"/myhome/grandfloor/kitchen/temperature","message":"25 degree"}'
pub-bedroom-on: '{"command":"publish","topic":"/myhome/grandfloor/bedroom/temperature","message":"28 degree","autoDelete":true}'
pub-bedroom-off: '{"command":"publish","topic":"/myhome/grandfloor/bedroom/temperature","message":"28 degree","autoDelete":false}'
pub-kitchen-reply: '{"command":"publish","topic":"/myhome/grandfloor/kitchen/temperature","message":"25 degree","reply":true}'
